#pragma once

#include "sdkconfig.h"

// Ears
#define EAR_VOLTAGE_MV   CONFIG_NEKOMIMI_EAR_VOLTAGE
#define EAR_TDP_MW       CONFIG_NEKOMIMI_EAR_TDP_LIMIT
#define EAR_CNT          CONFIG_NEKOMIMI_EAR_NUM
#define EAR_GPIO_PWM_CLK CONFIG_NEKOMIMI_EAR_GPIO_PWM_CLK
#define EAR_GPIO_LATCH   CONFIG_NEKOMIMI_EAR_GPIO_LATCH

#ifdef CONFIG_NEKOMIMI_EAR_SPI_HSPI
#define EAR_SPI          HSPI_HOST
#endif

#ifdef CONFIG_NEKOMIMI_EAR_SPI_VSPI
#define EAR_SPI          VSPI_HOST
#endif

#ifdef CONFIG_NEKOMIMI_EAR_DEFAULT_CURRENT_3_2_mA
#define EAR_DEFAULT_CURRENT TLC_CURRENT_3_2_mA
#endif

#ifdef CONFIG_NEKOMIMI_EAR_DEFAULT_CURRENT_8_0_mA
#define EAR_DEFAULT_CURRENT TLC_CURRENT_8_0_mA
#endif

#ifdef CONFIG_NEKOMIMI_EAR_DEFAULT_CURRENT_11_2_mA
#define EAR_DEFAULT_CURRENT TLC_CURRENT_11_2_mA
#endif

#ifdef CONFIG_NEKOMIMI_EAR_DEFAULT_CURRENT_15_9_mA
#define EAR_DEFAULT_CURRENT TLC_CURRENT_15_9_mA
#endif

#ifdef CONFIG_NEKOMIMI_EAR_DEFAULT_CURRENT_19_1_mA
#define EAR_DEFAULT_CURRENT TLC_CURRENT_19_1_mA
#endif

#ifdef CONFIG_NEKOMIMI_EAR_DEFAULT_CURRENT_23_9_mA
#define EAR_DEFAULT_CURRENT TLC_CURRENT_23_9_mA
#endif

#ifdef CONFIG_NEKOMIMI_EAR_DEFAULT_CURRENT_27_1_mA
#define EAR_DEFAULT_CURRENT TLC_CURRENT_27_1_mA
#endif

#ifdef CONFIG_NEKOMIMI_EAR_DEFAULT_CURRENT_31_9_mA
#define EAR_DEFAULT_CURRENT TLC_CURRENT_31_9_mA
#endif

// Sensors
#define SENSOR_I2C_BUS_GPIO_SDA CONFIG_NEKOMIMI_SENSOR_I2C_GPIO_SDA
#define SENSOR_I2C_BUS_GPIO_SCL CONFIG_NEKOMIMI_SENSOR_I2C_GPIO_SCL
#define SENSOR_I2C_BUS_FREQ     CONFIG_NEKOMIMI_SENSOR_I2C_FREQ

#ifdef CONFIG_NEKOMIMI_SENSOR_I2C_0
#define SENSOR_I2C_BUS  I2C_NUM_0
#endif

#ifdef CONFIG_NEKOMIMI_SENSOR_I2C_1
#define SENSOR_I2C_BUS  I2C_NUM_1
#endif

// Environmental sensor
#ifdef CONFIG_NEKOMIMI_SENSOR_ENVIRON_BME680
#define NEKOMIMI_SENSOR_USE_BME680
#ifdef CONFIG_NEKOMIMI_SENSOR_ENVIRON_BME680_ADDR_PRIM
#define SENSOR_BME680_ADDR BME680_I2C_ADDR_PRIMARY
#endif

#ifdef CONFIG_NEKOMIMI_SENSOR_ENVIRON_BME680_ADDR_SEC
#define SENSOR_BME680_ADDR BME680_I2C_ADDR_SECONDARY
#endif
#endif

// Illuminance sensor
#ifdef CONFIG_NEKOMIMI_SENSOR_ILLUMINANCE_BH1750
#define NEKOMIMI_SENSOR_USE_BH1750
#ifdef CONFIG_NEKOMIMI_SENSOR_ILLUMINANCE_BH1750_ADDR_L
#define SENSOR_BH1750_ADDR BH1750_ADDR_L
#endif

#ifdef CONFIG_NEKOMIMI_SENSOR_ILLUMINANCE_BH1750_ADDR_H
#define SENSOR_BH1750_ADDR BH1750_ADDR_H
#endif
#endif

// Magnetometer
#ifdef CONFIG_NEKOMIMI_SENSOR_MAGNETO_LIS3MDL
#define NEKOMIMI_SENSOR_USE_LIS3MDL
#define SENSOR_LIS3MDL_GPIO_DRDY CONFIG_NEKOMIMI_SENSOR_MAGNETO_LIS3MDL_GPIO_DRDY
#define SENSOR_LIS3MDL_GPIO_INT CONFIG_NEKOMIMI_SENSOR_MAGNETO_LIS3MDL_GPIO_INT

#ifdef CONFIG_NEKOMIMI_SENSOR_MAGNETO_LIS3MDL_ADDR_L
#define SENSOR_LIS3MDL_ADDR LIS3MDL_ADDR_L
#endif

#ifdef CONFIG_NEKOMIMI_SENSOR_MAGNETO_LIS3MDL_ADDR_H
#define SENSOR_LIS3MDL_ADDR LIS3MDL_ADDR_H
#endif
#endif

